### ISSUE TITLE
关于安装方法的一个问题

### ISSUE THREAD

**Issue by tuxinghuan** [alfredcai/Rhea-Shanghai-University#1]
学长，Chorme 69版本现在不支持直接导入非 Chrome 网上应用店中发布的扩展程序了，所以方法二引入会导致无法使用插件，只能用方法一了。第一次在GitHub上提Issues，如果哪里有错还请学长指出。

**Comment by voldikss** [comment]
只是 Windows 系统不能这样，我记得 Linux 和 Mac 系统还是可以这样的。而且 Windows 系统 Chrome dev 版本也是可以的。（不知啥时候 watch 的，邮件收到提醒就来回复了 :neckbeard: ）

**Comment by tuxinghuan** [comment]
刚在mac上试了下也不行啊:sweat:

**Comment by voldikss** [comment]
呀，那就是条款更新了，我记得当时是这样的 https://chrome.googleblog.com/2014/05/protecting-chrome-users-from-malicious.html 😅

**Comment by tuxinghuan** [comment]
对啊...貌似九月份刚改呢...

**Comment by alfredcai** [comment]
@tuxinghuan @voldikss 发现终于我的代码有人看了，还是十分**感激**两位的。
我试了下，先在 `chrome://extensions/`页面下开启`开发者模式`后`刷新页面`还是能成功导入。MacOS 和 Ubuntu下的 Chrome 版本都是 71.0.3578.80 均成功导入。Windows下我暂时没有试成功。
教导处的页面我已经进不去啦，里面页面有没有改版，这份代码还有没有用，我都已经不能保证了。愿还能帮助到你~
其实安装方法一和方法二是差不多的，方法二只是我生成了秘钥进行了程序打包，更方便各个电脑之间互传而已。现在被 Google 禁了的话，方法一其实也没麻烦到哪里去。

**Comment by tuxinghuan** [comment]
嗯，因为我最近正好在学JS，所以看到这个就想着看看源码，然后春季选课的时候我试试能不能用吧，如果改版了我可能尽量解决一下，然后争取加一些新功能进去再PR吧，感谢学长。
